#
# Copyright (c) 2023, Arjuna Technologies Limited, Newcastle upon Tyne, Tyne and Wear, UK.
#

apiVersion: v1
kind: Pod
metadata:
  name: demo-sde
spec:
  containers:
  - name: activemq
    image: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:latest
    ports:
    - containerPort: 8161
      hostPort: 8361
    - containerPort: 5672
      hostPort: 5872
    env:
      - name: AMQ_USER
        value: "admin"
      - name: AMQ_PASSWORD
        value: "password"
  - name: webportal
    image: docker.io/risbic/sde-webportal:gt
    ports:
    - containerPort: 80
      hostPort: 8082
  - name: mongo
    image: docker.io/library/mongo:latest
    volumeMounts:
      - mountPath: /data/db
        name: mongo-data
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "admin"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "password"
  - name: minio
    image: quay.io/minio/minio
    volumeMounts:
      - mountPath: /data
        name: minio-data
    env:
      - name: MINIO_ROOT_USER
        value: "admin"
      - name: MINIO_ROOT_PASSWORD
        value: "password"
    args: ["server", "/data", "--address", ":9000", "--console-address", ":9001"]
  - name: request_receiver
    image: docker.io/risbic/sde-request-receiver:gt
  - name: request_checker
    image: docker.io/risbic/sde-request-checker:gt
  - name: analysis-adaptor
    image: docker.io/risbic/sde-analysis-adaptor:gt
  - name: response-checker
    image: docker.io/risbic/sde-response-checker:gt
  - name: response-sender
    image: docker.io/risbic/sde-response-sender:gt
  - name: control
    image: docker.io/risbic/sde-control:gt
  volumes:
    - name: mongo-data
      hostPath:
        path: ./sde-data/mongo
        type: DirectoryOrCreate
    - name: minio-data
      hostPath:
        path: ./sde-data/minio
        type: DirectoryOrCreate
