---
openapi: 3.1.0
paths:
  /block_request:
    post:
      parameters:
      - name: requestid
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
      summary: Post Block Request
      tags:
      - RO Crate Block Request
  /list_request_checkers:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JsonObject"
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JsonObject"
      summary: Post List Request Checkers
      tags:
      - RO Crate List Request Checkers
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JsonObject"
      summary: Get List Request Checkers
      tags:
      - RO Crate List Request Checkers
  /permit_request:
    post:
      parameters:
      - name: requestid
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
      summary: Post Permit Request
      tags:
      - RO Crate Permit Request
  /unchecked_request:
    get:
      parameters:
      - name: requestid
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
                format: binary
      summary: Get Unchecked Request
      tags:
      - RO Crate Unchecked Request
  /unchecked_requests:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
      summary: Get Unchecked Request Ids
      tags:
      - RO Crate Unchecked Requests
components:
  schemas:
    JsonObject:
      type: array
      items:
        type: object
        properties:
          key:
            type: string
          value: {}
info:
  title: sde-request-checker API
  version: 1.0.0-SNAPSHOT
servers:
- url: http://localhost:7010
  description: Auto generated value
- url: http://0.0.0.0:7010
  description: Auto generated value
