#
# Containerfile for Armadillo 3.3 Server for DataSHIELD testing
#

FROM ubuntu:latest

COPY molgenis-armadillo-3.3.0.jar .
COPY application-local.yml .

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y openjdk-17-jdk
RUN mkdir -p data

ENV SPRING_PROFILES_ACTIVE=basic

CMD java -Dspring.config.additional-location="application-local.yml" -jar molgenis-armadillo-3.3.0.jar
