#
# Copyright (c) 2023, TRE-FX Consortium Members
# Copyright (c) 2023-2024, Arjuna Technologies Limited, Newcastle upon Tyne, Tyne and Wear, UK.
#

ASCIIDOCTOR = asciidoctor

all:
	$(ASCIIDOCTOR) --destination-dir ../docs network_zones.adoc
