#
# Copyright (c) 2023, TRE-FX Consortium Members
# Copyright (c) 2023-2025, Arjuna Technologies Limited, Newcastle upon Tyne, Tyne and Wear, UK.
#

FROM quay.io/jitesoft/nginx

COPY dist/sde/browser /usr/local/nginx/html
COPY nginx.default.template /usr/local/default.template

EXPOSE 80
